name: Markdown Link Check

on:
  schedule:
    - cron: '0 3 * * 1'  # every Monday at 03:00 UTC
  pull_request:
  workflow_dispatch:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          config-file: '.github/mlc_config.json'
